In [4]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.14.0


In [6]:
# Tạo một số vô hướng (tensor bậc 0)
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# tạo 1 số vô hướng (tensor bậc 0)
scalar = tf.constant(7)
scalar

NameError: ignored

In [7]:
# Kiểm tra số chiều của tensor (ndim là số chiều)
scalar.ndim

0

In [8]:
# Tạo một vectơ (nhiều hơn 0 chiều)
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [9]:
vector.ndim

1

In [10]:
# Tạo một ma trận (nhiều hơn 1 chiều)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [11]:
import tensorflow as tf
print(tf.__version__)

2.14.0


In [13]:
# Tạo một ma trận khác và xác định kiểu dữ liệu
another = tf.constant([[10, 7],
                       [3., 2.],
                       [8., 9.]], dtype=tf.float16)

another

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [14]:
another.ndim

2

In [15]:
# Còn tensor thì sao? (có nhiều hơn 2 chiều, dù tất cả các mục trên đều là các tensor về mặt kỹ thuật)
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],

                      [[7, 8, 9],
                       [10, 11, 12]],

                      [[13, 14, 15],
                       [16, 17, 18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [16]:
tensor.ndim

3

In [17]:
# Tạo tensor tương tự với tf.Variable() và tf.constant()
changeable = tf.Variable([10, 7])
unchangeable = tf.constant([10, 7])

changeable, unchangeable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [18]:
# Sẽ có lỗi (yêu cầu phương thức .assign())
changeable[0] = 10
changeable

TypeError: ignored

In [19]:
# khong co loi
changeable[0].assign(6)
changeable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([6, 7], dtype=int32)>

Thay đổi giá trị trong tensor tf.constant()

In [20]:
unchangeable[0].assign(6) # không thể thay đổi giá trị hằng số
unchangeable

AttributeError: ignored

## Tạo Random tensor

In [21]:
# Tạo 2 random tensor (nhưng tương tự nhau)
random1 = tf.random.Generator.from_seed(42) # Thiết lập seed cho khả năng tái tạo
random1 = random1.normal(shape=(3, 2)) # Tạo tensor từ phân phối chính
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape=(3, 2))

random1, random2, random1 == random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [22]:
# Tạo 2 random tensor (khác nhau)
random3 = tf.random.Generator.from_seed(42)
random3 = random3.normal(shape=(3, 2))
random4 = tf.random.Generator.from_seed(42)
random4 = random4.normal(shape=(3, 2))

random3, random4, random3 == random4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [23]:
not_shuff = tf.Variable([[3, 4],
                        [2, 5],
                        [10, 7]])

In [24]:
# Xáo trộn tensor (có giá trị khi chúng ta xáo trộn dữ liệu)
# Mỗi lần lại lại nhận được các kết quả khác nhau
tf.random.shuffle(not_shuff)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [25]:
# Xáo trộn theo thứ tự tương tự
# Thiết lập global random seed
tf.random.set_seed(42)

# Thiết lập operation random seed
tf.random.shuffle(not_shuff, seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [26]:
# Xáo trộn theo thứ tự tương tự mỗi lần sử dụng tham số seed (sẽ không thực sự như nhau)
tf.random.shuffle(not_shuff, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [27]:
# Xáo trộn theo thứ tự tương tự
# Thiết lập global random seed
tf.random.set_seed(42)

# Thiết lập operation random seed
tf.random.shuffle(not_shuff, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [28]:
# Thiết lập global random seed
tf.random.set_seed(42) #nếu biến đổi nó thành chú thích, chúng ta sẽ nhận được các kết quả khác nhau

# Thiết lập operation random seed
tf.random.shuffle(not_shuff)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

## Các cách khác để tạo tensor

In [29]:
# Tạo tensor có các giá trị 1
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [30]:
tf.zeros(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [31]:
import numpy as np

In [32]:
numpy_A = np.arange(1,31, dtype=np.int32)
A = tf.constant(numpy_A, shape=[2, 5, 3])
# # lưu ý: tổng shape (2*4*3) phải khớp với số phần tử trong mảng
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], dtype=int32),
 <tf.Tensor: shape=(2, 5, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12],
         [13, 14, 15]],
 
        [[16, 17, 18],
         [19, 20, 21],
         [22, 23, 24],
         [25, 26, 27],
         [28, 29, 30]]], dtype=int32)>)

## **Lấy thông tin từ tensor (shape, rank, size)**
 - Shape (hình dạng): Độ dài (số phần tử) của từng chiều của tensor.
  - Rank (bậc): Số chiều của tensor.
  - Axis (trục) or Dimension (chiều): Các chiều cụ thể của tensor.
  - Size (kích thước): Tổng số mục trong tensor.


In [33]:
rank4 = tf.zeros([2,3,4,5])
rank4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [34]:
rank4.shape, rank4.ndim, tf.size(rank4)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [35]:
# Lấy nhiều thuộc tính của tensor
print("Datatype of every element:", rank4.dtype)
print("Number of dimensions (rank):", rank4.ndim)
print("Shape of tensor:", rank4.shape)
print("Elements along axis 0 of tensor:", rank4.shape[0])
print("Elements along last axis of tensor:", rank4.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank4).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


## Chúng ta cũng có thể lập chỉ mục tensor như Python list.


In [36]:
# Lấy 2 mục đầu tiên của mỗi chiều
rank4[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [37]:
# Lấy chiều từ mỗi chỉ mục trừ chỉ mục cuối
rank4[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [38]:
# Tạo tensor bậc 2 (2 chiều)
rank2 = tf.constant([[10, 7],
                     [2, 3]])

# Lấy mục cuối của mỗi hàng
rank2[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 3], dtype=int32)>

In [39]:
# Thêm một chiều bổ sung (vào cuối)
rank3 = rank2[..., tf.newaxis]
rank2, rank3

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 2,  3]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 2],
         [ 3]]], dtype=int32)>)

In [40]:
tf.expand_dims(rank2, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 3]]], dtype=int32)>

### **Thao tác tensor** (Các phép toán)

In [41]:
# Có thể cộng thêm giá trị vào tensor sử dụng toán tử cộng
tensor = tf.constant([[10,5], [1,6]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 15],
       [11, 16]], dtype=int32)>

In [42]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 25],
       [ 5, 30]], dtype=int32)>

In [43]:
tensor - 6

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4, -1],
       [-5,  0]], dtype=int32)>

In [44]:
# Sử dụng hàm TensorFlow tương đương của toán tử '*' (nhân)
tf.multiply(tensor, 3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 15],
       [ 3, 18]], dtype=int32)>

In [45]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  5],
       [ 1,  6]], dtype=int32)>

In [46]:
# Nhân ma trận
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[105,  80],
       [ 16,  41]], dtype=int32)>

In [47]:
# Phép nhân ma trận với toán tử '@' của Python
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[105,  80],
       [ 16,  41]], dtype=int32)>

In [48]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [49]:
X @ Y

InvalidArgumentError: ignored

In [50]:
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [51]:
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [52]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [53]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [54]:
# Tích vô hướng
# Thực hiện tích vô hướng trên X và Y (cần X là chuyển vị)

tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [55]:
# Thực hiện phép nhân ma trận giữa X và Y (chuyển vị)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [56]:
# Thực hiện phép nhân ma trận giữa X và Y (rehaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [57]:
# Kiểm tra shape của Y, Y đã reshape và Y chuyển vị
Y.shape, tf.reshape(Y, (2,3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [58]:
# Kiểm tra shape của Y, Y đã reshape và Y chuyển vị
print("Normal Y:")
print(Y, "\n") # "\n" cho dòng mới

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


### **Thay đổi kiểu dữ liệu của tensor**

In [59]:
B = tf.constant([1.9, 7.5])

C = tf.constant([1, 7])

B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.9, 7.5], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [60]:
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.9, 7.5], dtype=float16)>

In [61]:
C = tf.cast(C, dtype=tf.float16)
C

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 7.], dtype=float16)>

#### Lấy giá trị tuyệt đối

In [62]:
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [63]:
D = tf.abs(D)
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### Tìm min, max, mean, sum (kết tập)

In [64]:
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([88, 20, 16, 73, 64, 41, 45, 59, 20, 89, 56, 11, 11, 52, 53, 76, 87,
       40, 67,  0, 16, 14, 93, 54, 72, 87, 76, 85,  7, 48,  4, 72,  0, 78,
       98, 21, 97, 67, 25, 54, 74, 86,  6,  8, 26, 35, 27, 20, 32, 38])>

In [65]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [66]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [67]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [68]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2388>

### Tìm giá trị lớn nhất và nhỏ nhất theo vị trí

In [69]:
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.36841181, 0.19745779, 0.35040935, 0.22311563, 0.14386603,
       0.69459031, 0.56482023, 0.16443903, 0.12167251, 0.37338418,
       0.3360248 , 0.8342423 , 0.83276832, 0.92303956, 0.92557007,
       0.20827502, 0.26588231, 0.7237949 , 0.95125019, 0.70430774,
       0.29313474, 0.39391561, 0.91567102, 0.4539661 , 0.64673228,
       0.37251796, 0.12038616, 0.62461288, 0.21921967, 0.0276262 ,
       0.91923313, 0.31641814, 0.91617205, 0.79643639, 0.11512043,
       0.87286669, 0.72412252, 0.9988429 , 0.59794427, 0.18336654,
       0.00347784, 0.9866266 , 0.39932759, 0.07126391, 0.1988165 ,
       0.29142923, 0.40172501, 0.98681821, 0.14495492, 0.96635417])>

In [70]:
# Tìm vị trí phần tử lớn nhất của F
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=37>

In [71]:
# Tìm vị trí phần tử nhỏ nhất của F
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=40>

In [73]:
# Tìm vị trí phần tử lớn nhất của F
print(f"Vị tí phần tử max: {tf.argmax(F).numpy()}")
print(f"Giá trị max: {tf.reduce_max(F).numpy()}")
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

Vị tí phần tử max: 37
Giá trị max: 0.9988429003950644
Using tf.argmax() to index F, the maximum value of F is: 0.9988429003950644
Are the two max values the same (they should be)? True


### **Nén tensor (loại tất cả các chiều đơn lẻ)**

In [74]:
# Tạo một tensor bậc 5 (5 chiều) có 50 số trong khoảng 0-100
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [75]:
G_sque = tf.squeeze(G)
G_sque.shape, G_sque.ndim

(TensorShape([50]), 1)

### Mã hóa One-hot

In [76]:
# Tạo một danh sách các chỉ số
lists = [0, 1, 2, 3]

# Mã hóa one-hot chúng
tf.one_hot(lists, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [77]:
# Specify custom values for on and off encoding
tf.one_hot(lists, depth=4, on_value='Live', off_value='Offline')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Live', b'Offline', b'Offline', b'Offline'],
       [b'Offline', b'Live', b'Offline', b'Offline'],
       [b'Offline', b'Offline', b'Live', b'Offline'],
       [b'Offline', b'Offline', b'Offline', b'Live']], dtype=object)>

### **Bình phương, log, căn bậc hai**

In [78]:
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [79]:
# Bình phương nó
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [80]:
# Tính căn bậc hai (không lỗi), không phải là số nguyên
tf.sqrt(H)

InvalidArgumentError: ignored

In [82]:
# Đổi H thành float32
H = tf.cast(H, dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [83]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [84]:
# Tính log (đầu vào cần là float)
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Thao tác tf.Variable tensor

In [85]:
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [86]:
I.assign([0, 1, 2, 3, 100])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([  0,   1,   2,   3, 100])>

In [87]:
# Thêm gia tri vào mỗi phần tử trong I
I.assign_add([10, 10, 10, 10, 15])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 10,  11,  12,  13, 115])>

# Tensor và NumPy

In [88]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [89]:
# Chuyển đổi tensor J thành mảng NumPy với np.array()
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [90]:
# Chuyển đổi tensor J thành mảng NumPy với .numpy()
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [91]:
numpyJ = tf.constant(np.array([3., 7., 10.])) # sẽ là float64 (do NumPy)
tensorJ = tf.constant([3., 7., 10.])  # sẽ là float32 (do mặc định là TensorFlow)
numpyJ.dtype, tensorJ.dtype

(tf.float64, tf.float32)

# Sử dụng @tf.function

In [100]:
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))

function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [102]:
@tf.function
def tf_function(x, y):
  return x**2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

## Tìm truy cập vào GPU

In [103]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [104]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [105]:
!nvidia-smi

Wed Nov  1 13:54:16 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P0    25W /  70W |    361MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------